"""Executable plan model — recreate and move actions, dry-run rendering only.

Per spec 0005 § Phase-gate invariant, this module is allowed to:
- Read the classify cache.
- Derive recreate commands from manifest evidence.
- Perform smoke-test reads of well-known integrity files at workspace depth 1.
- Emit plan JSON to `$XDG_STATE_HOME/clain/plans/`.

It is NOT allowed to spawn a process, mutate any path derived from ROOT, or
touch the destination of a move action. Those become available only when
spec 00NN lifts the dry-run gate.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from clain.placements import Placement, for_manifest
from clain.state import plan_dir, utc_now_filename_stamp, utc_now_iso, write_json

SCHEMA_VERSION = 1


@dataclass
class Action:
    workspace: str
    type: str  # "delete" | "recreate" | "move" | "smoke-test"
    target: str
    cls: str
    rationale: str
    commands: list[str] = field(default_factory=list)
    preconditions: list[str] = field(default_factory=list)
    safe_to_execute: bool = True
    unsafe_reason: str | None = None

    @property
    def id(self) -> str:
        h = hashlib.sha256(f"{self.workspace}|{self.type}|{self.target}".encode()).hexdigest()
        return h[:12]

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "workspace": self.workspace,
            "type": self.type,
            "target": self.target,
            "class": self.cls,
            "rationale": self.rationale,
            "commands": list(self.commands),
            "preconditions": list(self.preconditions),
            "safe_to_execute": self.safe_to_execute,
            "unsafe_reason": self.unsafe_reason,
        }


# ---- Manifest → recreate command derivation -----------------------------------------

# Order matters: first match wins. Pixi/uv beat raw pyproject.toml because they
# disambiguate the Python toolchain explicitly.
PYTHON_TOOLCHAIN_PRIORITY: tuple[tuple[str, str], ...] = (
    ("pixi.toml", "pixi install"),
    ("uv.lock", "uv sync"),
)

NODE_TOOLCHAIN_PRIORITY: tuple[tuple[str, str], ...] = (
    ("pnpm-lock.yaml", "pnpm install --frozen-lockfile"),
    ("package-lock.json", "npm ci"),
    ("yarn.lock", "yarn install --frozen-lockfile"),
)


def _derive_recreate(cls: str, manifests: set[str]) -> tuple[list[str], bool, str | None, Placement | None]:
    """Return (commands, safe_to_execute, unsafe_reason, placement_advice)."""
    if cls != "cache-managed":
        # ephemeral / bytecode are regenerated by normal use; no explicit recreate.
        return [], True, None, None

    # Python branch: look for explicit toolchain first.
    for manifest, cmd in PYTHON_TOOLCHAIN_PRIORITY:
        if manifest in manifests:
            return [cmd], True, None, for_manifest(manifest)

    # Node branch: lockfile is required for safety.
    for manifest, cmd in NODE_TOOLCHAIN_PRIORITY:
        if manifest in manifests:
            return [cmd], True, None, for_manifest(manifest)

    # Ambiguous Python: pyproject.toml or requirements.txt without an explicit toolchain.
    if "pyproject.toml" in manifests:
        return (
            ["# ambiguous: pick one of pixi/uv/poetry, then re-run plan"],
            False,
            "ambiguous Python toolchain — workspace has pyproject.toml but no pixi.toml / uv.lock / poetry.lock",
            None,
        )
    if "requirements.txt" in manifests:
        return (
            ["# ambiguous: pin a toolchain (uv pip / pip), then re-run plan"],
            False,
            "requirements.txt present but no toolchain lockfile",
            None,
        )

    # Node without lockfile.
    if "package.json" in manifests:
        return (
            ["# unsafe: no lockfile, recreate would resolve fresh versions"],
            False,
            "package.json without a lockfile — recreate would resolve fresh versions",
            None,
        )

    return (
        [],
        False,
        "no recognised manifest — investigate manually",
        None,
    )


def _rationale(cls: str, manifest_hits: list[str], placement: Placement | None) -> str:
    base_by_cls = {
        "cache-managed": "Cache-managed dir — belongs in a single store per ecosystem, outside the synced tree.",
        "ephemeral": "Ephemeral build output — regenerable by the normal build step.",
        "bytecode": "Bytecode / tool cache — regenerated on the next run.",
    }
    base = base_by_cls.get(cls, "Subtree.")
    manifest_note = f" Evidence: {', '.join(manifest_hits)}." if manifest_hits else ""
    placement_note = f" Placement: {placement.store_advice}" if placement else ""
    return f"{base}{manifest_note}{placement_note}"


def build_recreate_plan(classify_payload: dict[str, Any]) -> dict[str, Any]:
    actions: list[Action] = []
    for ws in classify_payload.get("workspaces", []):
        manifests = set(ws.get("manifests", []))
        for tag in ws.get("class_tags", []):
            cls = tag.get("class")
            rel = tag.get("relative_path")
            target = str(Path(ws.get("path", "")) / rel)
            commands, safe, unsafe_reason, placement = _derive_recreate(cls, manifests)
            # Manifests that contributed to the decision (for rationale evidence).
            manifest_hits = sorted(
                m
                for m in manifests
                if m
                in (
                    "pixi.toml",
                    "uv.lock",
                    "pyproject.toml",
                    "requirements.txt",
                    "pnpm-lock.yaml",
                    "package-lock.json",
                    "yarn.lock",
                    "package.json",
                )
            )
            rationale = _rationale(cls, manifest_hits, placement)

            actions.append(
                Action(
                    workspace=ws["name"],
                    type="delete",
                    target=target,
                    cls=cls,
                    rationale=rationale,
                    commands=[f"rm -rf {target!r}"],
                    safe_to_execute=safe,
                    unsafe_reason=unsafe_reason,
                )
            )
            if cls == "cache-managed":
                actions.append(
                    Action(
                        workspace=ws["name"],
                        type="recreate",
                        target=str(ws.get("path", "")),
                        cls=cls,
                        rationale=rationale,
                        commands=commands,
                        preconditions=[f"delete action for {target!r} must complete first"],
                        safe_to_execute=safe,
                        unsafe_reason=unsafe_reason,
                    )
                )

    return _wrap_plan("recreate", classify_payload, actions)


def build_move_plan(classify_payload: dict[str, Any], destination_root: Path) -> dict[str, Any]:
    actions: list[Action] = []
    for ws in classify_payload.get("workspaces", []):
        if not ws.get("in_sync_tree"):
            continue
        manifests = set(ws.get("manifests", []))
        source = ws.get("path", "")
        destination = str(destination_root / ws["name"])

        # Smoke test: integrity findings.
        preconditions: list[str] = []
        has_venv = any(t.get("relative_path", "").startswith((".venv", "venv")) for t in ws.get("class_tags", []))
        if has_venv:
            preconditions.append(
                "venv directories embed absolute paths in pyvenv.cfg and console "
                "scripts — delete-and-recreate via `clain plan recreate`, do not move."
            )
        if ".envrc" in manifests:
            preconditions.append(".envrc may contain absolute path references — review before move.")
        if "docker-compose.yml" in manifests or "docker-compose.yaml" in manifests:
            preconditions.append("docker-compose.* may reference absolute paths or bind-mounted volumes.")
        has_lockfile = bool(
            manifests
            & {
                "uv.lock",
                "pixi.lock",
                "poetry.lock",
                "pnpm-lock.yaml",
                "package-lock.json",
                "yarn.lock",
            }
        )
        safe = has_lockfile or not any(t.get("class") == "cache-managed" for t in ws.get("class_tags", []))
        unsafe_reason = (
            None
            if safe
            else "cache-managed subtrees present but no lockfile — recreate after move would resolve fresh versions"
        )

        actions.append(
            Action(
                workspace=ws["name"],
                type="smoke-test",
                target=source,
                cls="workspace-source",
                rationale="Integrity scan over manifests + integrity files at workspace root.",
                commands=[],
                preconditions=preconditions,
                safe_to_execute=True,
            )
        )
        actions.append(
            Action(
                workspace=ws["name"],
                type="move",
                target=destination,
                cls="workspace-source",
                rationale=(
                    "Workspace is inside the synced tree. Move source out; "
                    "cache-managed subtrees (if any) must be excluded from the move and "
                    "regenerated via `clain plan recreate` against the new location."
                ),
                commands=[
                    f"rsync -a --delete "
                    f"--exclude node_modules --exclude .venv --exclude venv "
                    f"--exclude site-packages --exclude __pycache__ "
                    f"--exclude dist --exclude build --exclude .next --exclude .cache "
                    f"{source!r}/ {destination!r}/"
                ],
                preconditions=preconditions,
                safe_to_execute=safe,
                unsafe_reason=unsafe_reason,
            )
        )

    return _wrap_plan("move", classify_payload, actions)


def _wrap_plan(kind: str, classify_payload: dict[str, Any], actions: list[Action]) -> dict[str, Any]:
    scan = classify_payload.get("scan", {})
    unsafe = sum(1 for a in actions if not a.safe_to_execute)
    workspaces = {a.workspace for a in actions}
    return {
        "schema": SCHEMA_VERSION,
        "kind": kind,
        "generated_at": utc_now_iso(),
        "root": scan.get("root"),
        "classify_cache_id": f"{scan.get('root')}|{scan.get('ended_at')}",
        "actions": [a.to_dict() for a in actions],
        "summary": {
            "workspace_count": len(workspaces),
            "action_count": len(actions),
            "unsafe_count": unsafe,
        },
    }


def persist_plan(plan: dict[str, Any]) -> Path:
    kind = plan.get("kind", "plan")
    stamp = utc_now_filename_stamp()
    out = plan_dir() / f"{kind}-{stamp}.json"
    write_json(out, plan)
    return out
